version: 2

jobs:
  build:
    working_directory: ~/egovernment/eregistrations
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
    steps:
      - checkout
      - run:
          working_directory: ~/egovernment
          command: git clone git@github.com:egovernment/eregistrations-lomas.git eregistrations-lomas
      - run:
          working_directory: ~/egovernment/eregistrations-lomas
          command: rm -r node_modules/eregistrations
      - run:
          working_directory: ~/egovernment/eregistrations-lomas
          command: ln -s ~/egovernment/eregistrations node_modules/
      - run: ln -s ~/egovernment/eregistrations-lomas/node_modules .
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          working_directory: ~/egovernment/eregistrations
          command: nvm install 4 && nvm alias default 4
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: echo "ignore"
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
      - run: npm run ci
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
